name: compass_example
description: Demonstrates how to use the compass plugin.
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  compass:
    path: ../

  cupertino_icons: ^1.0.0
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
